server {
	listen 80;
	server_name _;
	root /app;
	index index.php;

	client_max_body_size 128m;

	location ^~ /content/profile_avatars/ {
		expires 7d;
		access_log off;
		try_files $uri =404;
	}

	location ^~ /content/ {
		deny all;
		return 403;
	}

	location = /json {
		rewrite ^ /json.php last;
	}

	location = /json/ {
		rewrite ^ /json.php last;
	}

	location / {
		try_files $uri $uri/ @hotglue;
	}

	location @hotglue {
		rewrite ^/(.*)$ /index.php?$1 last;
	}

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param SCRIPT_NAME $fastcgi_script_name;
		fastcgi_pass php:9000;
	}

	location ~* \.(css|gif|ico|jpeg|jpg|js|png|webp|woff)$ {
		expires 7d;
		access_log off;
		try_files $uri =404;
	}
}
